# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: .distro/spglib.spec

# add or remove files that should be synced
files_to_sync:
  - src: .distro/spglib.spec
    dest: spglib.spec
  - .packit.yaml
  - src: .distro/spglib.rpmlintrc
    dest: spglib.rpmlintrc
  # tmt setup
  - src: .distro/.fmf/
    dest: .fmf/
  - src: .distro/plans/
    dest: plans/
    filters:
      - "- main.fmf.dist-git"
      - "- rpmlint.fmf"
  - src: .distro/plans/main.fmf.dist-git
    dest: plans/main.fmf
upstream_package_name: spglib
downstream_package_name: spglib
update_release: false
upstream_tag_template: v{version}

jobs:
  - job: copr_build
    trigger: pull_request
    owner: lecris
    project: spglib
    update_release: true
    release_suffix: "{PACKIT_RPMSPEC_RELEASE}"
    additional_repos:
      - copr://@scikit-build/release
    targets:
      # TODO: Switch to fedora-all once F37 support is dropped
      - fedora-development-x86_64
      - fedora-latest-x86_64
      - fedora-latest-stable-x86_64
      - fedora-development-aarch64
      - fedora-latest-aarch64
      - fedora-latest-stable-aarch64
  - job: tests
    trigger: pull_request
    targets:
      - fedora-development-x86_64
      - fedora-latest-x86_64
      - fedora-latest-stable-x86_64
      - fedora-development-aarch64
      - fedora-latest-aarch64
      - fedora-latest-stable-aarch64
    fmf_path: .distro
  - job: copr_build
    trigger: commit
    branch: develop
    owner: lecris
    project: nightly
    additional_repos:
      - copr://@scikit-build/release
    targets:
      - fedora-development-x86_64
      - fedora-latest-x86_64
      - fedora-latest-stable-x86_64
      - fedora-development-aarch64
      - fedora-latest-aarch64
      - fedora-latest-stable-aarch64
  - job: copr_build
    trigger: release
    owner: lecris
    project: release
    targets:
      - fedora-development-x86_64
      - fedora-latest-x86_64
      - fedora-latest-stable-x86_64
      - fedora-development-aarch64
      - fedora-latest-aarch64
      - fedora-latest-stable-aarch64
  - job: tests
    trigger: commit
    branch: develop
    targets:
      - fedora-development-x86_64
      - fedora-latest-x86_64
      - fedora-latest-stable-x86_64
      - fedora-development-aarch64
      - fedora-latest-aarch64
      - fedora-latest-stable-aarch64
    fmf_path: .distro
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-rawhide
  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all
  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched
