version: 2

python:
  install:
    - path: .
      extra_requirements:
        - docs
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - echo "Placeholder for doxygen builds via cmake"
sphinx:
  configuration: doc/conf.py
