version: 2

python:
  install:
    - path: .
      extra_requirements:
        - docs
build:
  os: ubuntu-22.04
  tools:
    python: "3"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
sphinx:
  configuration: doc/conf.py
