package:
  name: spglib
  version: version_from_shell

source:
  git_url: https://github.com/spglib/spglib.git
  git_branch: {{ environ.get('GIT_BRANCH','master') }}

build:
  script_env:
    - GIT_BRANCH
  #  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - spglib = spglib:main
    #
    # Would create an entry point called spglib that calls spglib.main()

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
# number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  number: 0

requirements:
  build:
    - python
    - numpy>=1.11

  run:
    - python
    - numpy>=1.11
    - pyyaml

test:
  source_files:
    - python/test
  requires:
    - python
    - numpy
    - pyyaml
  # Python imports
  imports:
    - spglib

#  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

#  requires:
    # Put any additional test requirements here.  For example
    #- nose

about:
  home: https://spglib.github.io/spglib/
  license: BSD
  summary: 'Space symmetry groups spglib module.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
