name: release
run-name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"

jobs:
  tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  pypi-wheel:
    needs: [ tests ]
    uses: ./.github/workflows/pypi-wheel-builds.yml
    secrets: inherit
  upload_pypi:
    name: Upload to PyPI repository
    needs: [ tests, pypi-wheel ]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/spglib/
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - name: Publish package to TestPyPI
        if: ${{ contains(github.ref, 'rc') }}
        # TODO: Maybe we can move this to main PyPI since it is marked rc
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
      - name: Publish package to PyPI
        if: ${{ !contains(github.ref, 'rc') }}
        uses: pypa/gh-action-pypi-publish@release/v1
  release:
    needs: [ upload_pypi ]
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Get python packages
        run: pip install .[doc]
      - name: Prepare release notes
        run: scripts/generate_changelog.py --release ${{ github.ref_name }} --type tag
      - uses: softprops/action-gh-release@v1
        with:
          name: Spglib ${{ github.ref_name }}
          body_path: ChangeLog.md
          draft: true
          prerelease: ${{ contains(github.ref, 'rc') }}
          generate_release_notes: true
